### ISSUE TITLE
`@chakra-ui/react` version mismatch not detected

### ISSUE THREAD

**Issue by baptisteArno** [QuiiBz/sherif#64]
Running `pnpm dlx sherif@latest`, it does not detect `@chakra-ui/react` package mismatch from package paths:
- `apps/builder`
- `ee/apps/landing-page`

Project src: https://github.com/baptisteArno/typebot.io

I bumped `@chakra-ui/react` in `apps/builder`, then ran sherif but it could not figure out the version mismatch

**Comment by QuiiBz** [comment]
I added some debug logs and turns out we fail to parse the `package.json` inside `ee/apps/landing-page`, but ignore the error ([here](https://github.com/QuiiBz/sherif/blob/1e12eec1407240f996b1b97ec1df115aec169d83/src/collect.rs#L53)):

<img width="1246" alt="Screenshot 2024-06-18 at 08 53 02" src="https://github.com/QuiiBz/sherif/assets/43268759/83383908-d64b-47ee-951d-2e9b6b9f2489">

The issue is that the `private` field should be a boolean, not a string:

<img width="284" alt="Screenshot 2024-06-18 at 08 54 16" src="https://github.com/QuiiBz/sherif/assets/43268759/afe96464-534e-45a9-9a0d-8c3cf69a9065">

Sherif should also log that error instead of ignoring it, I'll send a PR later.

**Comment by QuiiBz** [comment]
Replacing with `"private": true` now works as expected, and surfaces a Prettier version mismatch:

<img width="965" alt="Screenshot 2024-06-18 at 08 55 23" src="https://github.com/QuiiBz/sherif/assets/43268759/699f4315-6db1-49f8-a251-fc868746f475">

**Comment by baptisteArno** [comment]
Amazing, thank you for the info 🙌
